name: ci

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: "1.22"

    - name: chkfmt
      run: scripts/chkfmt

    - name: xbuild
      run: scripts/xbuild

